export interface ICountryCode {
    name: string;
    code: string;
    countryCode: string;
}

export const codes: ICountryCode[] = [
    { "name": "Afghanistan", "code": "AF", "countryCode": "004" },
    { "name": "Åland Islands", "code": "AX", "countryCode": "248" },
    { "name": "Albania", "code": "AL", "countryCode": "008" },
    { "name": "Algeria", "code": "DZ", "countryCode": "012" },
    { "name": "American Samoa", "code": "AS", "countryCode": "016" },
    { "name": "Andorra", "code": "AD", "countryCode": "020" },
    { "name": "Angola", "code": "AO", "countryCode": "024" },
    { "name": "Anguilla", "code": "AI", "countryCode": "660" },
    { "name": "Antarctica", "code": "AQ", "countryCode": "010" },
    { "name": "Antigua and Barbuda", "code": "AG", "countryCode": "028" },
    { "name": "Argentina", "code": "AR", "countryCode": "032" },
    { "name": "Armenia", "code": "AM", "countryCode": "051" },
    { "name": "Aruba", "code": "AW", "countryCode": "533" },
    { "name": "Australia", "code": "AU", "countryCode": "036" },
    { "name": "Austria", "code": "AT", "countryCode": "040" },
    { "name": "Azerbaijan", "code": "AZ", "countryCode": "031" },
    { "name": "Bahamas", "code": "BS", "countryCode": "044" },
    { "name": "Bahrain", "code": "BH", "countryCode": "048" },
    { "name": "Bangladesh", "code": "BD", "countryCode": "050" },
    { "name": "Barbados", "code": "BB", "countryCode": "052" },
    { "name": "Belarus", "code": "BY", "countryCode": "112" },
    { "name": "Belgium", "code": "BE", "countryCode": "056" },
    { "name": "Belize", "code": "BZ", "countryCode": "084" },
    { "name": "Benin", "code": "BJ", "countryCode": "204" },
    { "name": "Bermuda", "code": "BM", "countryCode": "060" },
    { "name": "Bhutan", "code": "BT", "countryCode": "064" },
    { "name": "Bolivia (Plurinational State of)", "code": "BO", "countryCode": "068" },
    { "name": "Bonaire, Sint Eustatius and Saba", "code": "BQ", "countryCode": "535" },
    { "name": "Bosnia and Herzegovina", "code": "BA", "countryCode": "070" },
    { "name": "Botswana", "code": "BW", "countryCode": "072" },
    { "name": "Bouvet Island", "code": "BV", "countryCode": "074" },
    { "name": "Brazil", "code": "BR", "countryCode": "076" },
    { "name": "British Indian Ocean Territory", "code": "IO", "countryCode": "086" },
    { "name": "Brunei Darussalam", "code": "BN", "countryCode": "096" },
    { "name": "Bulgaria", "code": "BG", "countryCode": "100" },
    { "name": "Burkina Faso", "code": "BF", "countryCode": "854" },
    { "name": "Burundi", "code": "BI", "countryCode": "108" },
    { "name": "Cabo Verde", "code": "CV", "countryCode": "132" },
    { "name": "Cambodia", "code": "KH", "countryCode": "116" },
    { "name": "Cameroon", "code": "CM", "countryCode": "120" },
    { "name": "Canada", "code": "CA", "countryCode": "124" },
    { "name": "Cayman Islands", "code": "KY", "countryCode": "136" },
    { "name": "Central African Republic", "code": "CF", "countryCode": "140" },
    { "name": "Chad", "code": "TD", "countryCode": "148" },
    { "name": "Chile", "code": "CL", "countryCode": "152" },
    { "name": "China", "code": "CN", "countryCode": "156" },
    { "name": "Christmas Island", "code": "CX", "countryCode": "162" },
    { "name": "Cocos (Keeling) Islands", "code": "CC", "countryCode": "166" },
    { "name": "Colombia", "code": "CO", "countryCode": "170" },
    { "name": "Comoros", "code": "KM", "countryCode": "174" },
    { "name": "Congo", "code": "CG", "countryCode": "178" },
    { "name": "Congo (Democratic Republic of the)", "code": "CD", "countryCode": "180" },
    { "name": "Cook Islands", "code": "CK", "countryCode": "184" },
    { "name": "Costa Rica", "code": "CR", "countryCode": "188" },
    { "name": "Côte d'Ivoire", "code": "CI", "countryCode": "384" },
    { "name": "Croatia", "code": "HR", "countryCode": "191" },
    { "name": "Cuba", "code": "CU", "countryCode": "192" },
    { "name": "Curaçao", "code": "CW", "countryCode": "531" },
    { "name": "Cyprus", "code": "CY", "countryCode": "196" },
    { "name": "Czechia", "code": "CZ", "countryCode": "203" },
    { "name": "Denmark", "code": "DK", "countryCode": "208" },
    { "name": "Djibouti", "code": "DJ", "countryCode": "262" },
    { "name": "Dominica", "code": "DM", "countryCode": "212" },
    { "name": "Dominican Republic", "code": "DO", "countryCode": "214" },
    { "name": "Ecuador", "code": "EC", "countryCode": "218" },
    { "name": "Egypt", "code": "EG", "countryCode": "818" },
    { "name": "El Salvador", "code": "SV", "countryCode": "222" },
    { "name": "Equatorial Guinea", "code": "GQ", "countryCode": "226" },
    { "name": "Eritrea", "code": "ER", "countryCode": "232" },
    { "name": "Estonia", "code": "EE", "countryCode": "233" },
    { "name": "Eswatini", "code": "SZ", "countryCode": "748" },
    { "name": "Ethiopia", "code": "ET", "countryCode": "231" },
    { "name": "Falkland Islands (Malvinas)", "code": "FK", "countryCode": "238" },
    { "name": "Faroe Islands", "code": "FO", "countryCode": "234" },
    { "name": "Fiji", "code": "FJ", "countryCode": "242" },
    { "name": "Finland", "code": "FI", "countryCode": "246" },
    { "name": "France", "code": "FR", "countryCode": "250" },
    { "name": "French Guiana", "code": "GF", "countryCode": "254" },
    { "name": "French Polynesia", "code": "PF", "countryCode": "258" },
    { "name": "French Southern Territories", "code": "TF", "countryCode": "260" },
    { "name": "Gabon", "code": "GA", "countryCode": "266" },
    { "name": "Gambia", "code": "GM", "countryCode": "270" },
    { "name": "Georgia", "code": "GE", "countryCode": "268" },
    { "name": "Germany", "code": "DE", "countryCode": "276" },
    { "name": "Ghana", "code": "GH", "countryCode": "288" },
    { "name": "Gibraltar", "code": "GI", "countryCode": "292" },
    { "name": "Greece", "code": "GR", "countryCode": "300" },
    { "name": "Greenland", "code": "GL", "countryCode": "304" },
    { "name": "Grenada", "code": "GD", "countryCode": "308" },
    { "name": "Guadeloupe", "code": "GP", "countryCode": "312" },
    { "name": "Guam", "code": "GU", "countryCode": "316" },
    { "name": "Guatemala", "code": "GT", "countryCode": "320" },
    { "name": "Guernsey", "code": "GG", "countryCode": "831" },
    { "name": "Guinea", "code": "GN", "countryCode": "324" },
    { "name": "Guinea-Bissau", "code": "GW", "countryCode": "624" },
    { "name": "Guyana", "code": "GY", "countryCode": "328" },
    { "name": "Haiti", "code": "HT", "countryCode": "332" },
    { "name": "Heard Island and McDonald Islands", "code": "HM", "countryCode": "334" },
    { "name": "Holy See", "code": "VA", "countryCode": "336" },
    { "name": "Honduras", "code": "HN", "countryCode": "340" },
    { "name": "Hong Kong", "code": "HK", "countryCode": "344" },
    { "name": "Hungary", "code": "HU", "countryCode": "348" },
    { "name": "Iceland", "code": "IS", "countryCode": "352" },
    { "name": "India", "code": "IN", "countryCode": "356" },
    { "name": "Indonesia", "code": "ID", "countryCode": "360" },
    { "name": "Iran (Islamic Republic of)", "code": "IR", "countryCode": "364" },
    { "name": "Iraq", "code": "IQ", "countryCode": "368" },
    { "name": "Ireland", "code": "IE", "countryCode": "372" },
    { "name": "Isle of Man", "code": "IM", "countryCode": "833" },
    { "name": "Israel", "code": "IL", "countryCode": "376" },
    { "name": "Italy", "code": "IT", "countryCode": "380" },
    { "name": "Jamaica", "code": "JM", "countryCode": "388" },
    { "name": "Japan", "code": "JP", "countryCode": "392" },
    { "name": "Jersey", "code": "JE", "countryCode": "832" },
    { "name": "Jordan", "code": "JO", "countryCode": "400" },
    { "name": "Kazakhstan", "code": "KZ", "countryCode": "398" },
    { "name": "Kenya", "code": "KE", "countryCode": "404" },
    { "name": "Kiribati", "code": "KI", "countryCode": "296" },
    { "name": "Korea (Democratic People's Republic of)", "code": "KP", "countryCode": "408" },
    { "name": "Korea (Republic of)", "code": "KR", "countryCode": "410" },
    { "name": "Kuwait", "code": "KW", "countryCode": "414" },
    { "name": "Kyrgyzstan", "code": "KG", "countryCode": "417" },
    { "name": "Lao People's Democratic Republic", "code": "LA", "countryCode": "418" },
    { "name": "Latvia", "code": "LV", "countryCode": "428" },
    { "name": "Lebanon", "code": "LB", "countryCode": "422" },
    { "name": "Lesotho", "code": "LS", "countryCode": "426" },
    { "name": "Liberia", "code": "LR", "countryCode": "430" },
    { "name": "Libya", "code": "LY", "countryCode": "434" },
    { "name": "Liechtenstein", "code": "LI", "countryCode": "438" },
    { "name": "Lithuania", "code": "LT", "countryCode": "440" },
    { "name": "Luxembourg", "code": "LU", "countryCode": "442" },
    { "name": "Macao", "code": "MO", "countryCode": "446" },
    { "name": "Macedonia (the former Yugoslav Republic of)", "code": "MK", "countryCode": "807" },
    { "name": "Madagascar", "code": "MG", "countryCode": "450" },
    { "name": "Malawi", "code": "MW", "countryCode": "454" },
    { "name": "Malaysia", "code": "MY", "countryCode": "458" },
    { "name": "Maldives", "code": "MV", "countryCode": "462" },
    { "name": "Mali", "code": "ML", "countryCode": "466" },
    { "name": "Malta", "code": "MT", "countryCode": "470" },
    { "name": "Marshall Islands", "code": "MH", "countryCode": "584" },
    { "name": "Martinique", "code": "MQ", "countryCode": "474" },
    { "name": "Mauritania", "code": "MR", "countryCode": "478" },
    { "name": "Mauritius", "code": "MU", "countryCode": "480" },
    { "name": "Mayotte", "code": "YT", "countryCode": "175" },
    { "name": "Mexico", "code": "MX", "countryCode": "484" },
    { "name": "Micronesia (Federated States of)", "code": "FM", "countryCode": "583" },
    { "name": "Moldova (Republic of)", "code": "MD", "countryCode": "498" },
    { "name": "Monaco", "code": "MC", "countryCode": "492" },
    { "name": "Mongolia", "code": "MN", "countryCode": "496" },
    { "name": "Montenegro", "code": "ME", "countryCode": "499" },
    { "name": "Montserrat", "code": "MS", "countryCode": "500" },
    { "name": "Morocco", "code": "MA", "countryCode": "504" },
    { "name": "Mozambique", "code": "MZ", "countryCode": "508" },
    { "name": "Myanmar", "code": "MM", "countryCode": "104" },
    { "name": "Namibia", "code": "NA", "countryCode": "516" },
    { "name": "Nauru", "code": "NR", "countryCode": "520" },
    { "name": "Nepal", "code": "NP", "countryCode": "524" },
    { "name": "Netherlands", "code": "NL", "countryCode": "528" },
    { "name": "New Caledonia", "code": "NC", "countryCode": "540" },
    { "name": "New Zealand", "code": "NZ", "countryCode": "554" },
    { "name": "Nicaragua", "code": "NI", "countryCode": "558" },
    { "name": "Niger", "code": "NE", "countryCode": "562" },
    { "name": "Nigeria", "code": "NG", "countryCode": "566" },
    { "name": "Niue", "code": "NU", "countryCode": "570" },
    { "name": "Norfolk Island", "code": "NF", "countryCode": "574" },
    { "name": "Northern Mariana Islands", "code": "MP", "countryCode": "580" },
    { "name": "Norway", "code": "NO", "countryCode": "578" },
    { "name": "Oman", "code": "OM", "countryCode": "512" },
    { "name": "Pakistan", "code": "PK", "countryCode": "586" },
    { "name": "Palau", "code": "PW", "countryCode": "585" },
    { "name": "Palestine, State of", "code": "PS", "countryCode": "275" },
    { "name": "Panama", "code": "PA", "countryCode": "591" },
    { "name": "Papua New Guinea", "code": "PG", "countryCode": "598" },
    { "name": "Paraguay", "code": "PY", "countryCode": "600" },
    { "name": "Peru", "code": "PE", "countryCode": "604" },
    { "name": "Philippines", "code": "PH", "countryCode": "608" },
    { "name": "Pitcairn", "code": "PN", "countryCode": "612" },
    { "name": "Poland", "code": "PL", "countryCode": "616" },
    { "name": "Portugal", "code": "PT", "countryCode": "620" },
    { "name": "Puerto Rico", "code": "PR", "countryCode": "630" },
    { "name": "Qatar", "code": "QA", "countryCode": "634" },
    { "name": "Réunion", "code": "RE", "countryCode": "638" },
    { "name": "Romania", "code": "RO", "countryCode": "642" },
    { "name": "Russian Federation", "code": "RU", "countryCode": "643" },
    { "name": "Rwanda", "code": "RW", "countryCode": "646" },
    { "name": "Saint Barthélemy", "code": "BL", "countryCode": "652" },
    { "name": "Saint Helena, Ascension and Tristan da Cunha", "code": "SH", "countryCode": "654" },
    { "name": "Saint Kitts and Nevis", "code": "KN", "countryCode": "659" },
    { "name": "Saint Lucia", "code": "LC", "countryCode": "662" },
    { "name": "Saint Martin (French part)", "code": "MF", "countryCode": "663" },
    { "name": "Saint Pierre and Miquelon", "code": "PM", "countryCode": "666" },
    { "name": "Saint Vincent and the Grenadines", "code": "VC", "countryCode": "670" },
    { "name": "Samoa", "code": "WS", "countryCode": "882" },
    { "name": "San Marino", "code": "SM", "countryCode": "674" },
    { "name": "Sao Tome and Principe", "code": "ST", "countryCode": "678" },
    { "name": "Saudi Arabia", "code": "SA", "countryCode": "682" },
    { "name": "Senegal", "code": "SN", "countryCode": "686" },
    { "name": "Serbia", "code": "RS", "countryCode": "688" },
    { "name": "Seychelles", "code": "SC", "countryCode": "690" },
    { "name": "Sierra Leone", "code": "SL", "countryCode": "694" },
    { "name": "Singapore", "code": "SG", "countryCode": "702" },
    { "name": "Sint Maarten (Dutch part)", "code": "SX", "countryCode": "534" },
    { "name": "Slovakia", "code": "SK", "countryCode": "703" },
    { "name": "Slovenia", "code": "SI", "countryCode": "705" },
    { "name": "Solomon Islands", "code": "SB", "countryCode": "090" },
    { "name": "Somalia", "code": "SO", "countryCode": "706" },
    { "name": "South Africa", "code": "ZA", "countryCode": "710" },
    { "name": "South Georgia and the South Sandwich Islands", "code": "GS", "countryCode": "239" },
    { "name": "South Sudan", "code": "SS", "countryCode": "728" },
    { "name": "Spain", "code": "ES", "countryCode": "724" },
    { "name": "Sri Lanka", "code": "LK", "countryCode": "144" },
    { "name": "Sudan", "code": "SD", "countryCode": "729" },
    { "name": "Suriname", "code": "SR", "countryCode": "740" },
    { "name": "Svalbard and Jan Mayen", "code": "SJ", "countryCode": "744" },
    { "name": "Sweden", "code": "SE", "countryCode": "752" },
    { "name": "Switzerland", "code": "CH", "countryCode": "756" },
    { "name": "Syrian Arab Republic", "code": "SY", "countryCode": "760" },
    { "name": "Taiwan, Province of China", "code": "TW", "countryCode": "158" },
    { "name": "Tajikistan", "code": "TJ", "countryCode": "762" },
    { "name": "Tanzania, United Republic of", "code": "TZ", "countryCode": "834" },
    { "name": "Thailand", "code": "TH", "countryCode": "764" },
    { "name": "Timor-Leste", "code": "TL", "countryCode": "626" },
    { "name": "Togo", "code": "TG", "countryCode": "768" },
    { "name": "Tokelau", "code": "TK", "countryCode": "772" },
    { "name": "Tonga", "code": "TO", "countryCode": "776" },
    { "name": "Trinidad and Tobago", "code": "TT", "countryCode": "780" },
    { "name": "Tunisia", "code": "TN", "countryCode": "788" },
    { "name": "Turkey", "code": "TR", "countryCode": "792" },
    { "name": "Turkmenistan", "code": "TM", "countryCode": "795" },
    { "name": "Turks and Caicos Islands", "code": "TC", "countryCode": "796" },
    { "name": "Tuvalu", "code": "TV", "countryCode": "798" },
    { "name": "Uganda", "code": "UG", "countryCode": "800" },
    { "name": "Ukraine", "code": "UA", "countryCode": "804" },
    { "name": "United Arab Emirates", "code": "AE", "countryCode": "784" },
    { "name": "United Kingdom of Great Britain and Northern Ireland", "code": "GB", "countryCode": "826" },
    { "name": "United States of America", "code": "US", "countryCode": "840" },
    { "name": "United States Minor Outlying Islands", "code": "UM", "countryCode": "581" },
    { "name": "Uruguay", "code": "UY", "countryCode": "858" },
    { "name": "Uzbekistan", "code": "UZ", "countryCode": "860" },
    { "name": "Vanuatu", "code": "VU", "countryCode": "548" },
    { "name": "Venezuela (Bolivarian Republic of)", "code": "VE", "countryCode": "862" },
    { "name": "Viet Nam", "code": "VN", "countryCode": "704" },
    { "name": "Virgin Islands (British)", "code": "VG", "countryCode": "092" },
    { "name": "Virgin Islands (U.S.)", "code": "VI", "countryCode": "850" },
    { "name": "Wallis and Futuna", "code": "WF", "countryCode": "876" },
    { "name": "Western Sahara", "code": "EH", "countryCode": "732" },
    { "name": "Yemen", "code": "YE", "countryCode": "887" },
    { "name": "Zambia", "code": "ZM", "countryCode": "894" },
    { "name": "Zimbabwe", "code": "ZW", "countryCode": "716" }
];
