# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: 
          name: Check if there is new package to install   
          command: |
              npm install
      - run: 
          name: Make postbuild.sh executable.
          command: |
              chmod +x ./postbuild.sh

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run build!
      - run: npm run build
      - deploy: 
          name: Deploy over SSH
          command: |
              scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r dist/* $SSH_USER@$SSH_HOST:/var/talaria-server/
      - run:
          name: Install packages over SSH
          command: |
              ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "cd /var/talaria-server && npm install"
      - run:
          name: Generate api via swagger-jsdoc over SSH
          command: |
              ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "cd /var/talaria-server && npm run generate:api"
      - run:
          name: Restart pm2 application process over SSH
          command: |
              ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "pm2 status && pm2 restart talaria-server"